### ISSUE TITLE
"Enable admin" option loops in Lineage OS 14.1 (Nougat) build making it impossible to enable SnooperStopper

### ISSUE THREAD

**Issue by natmey** [xmikos/SnooperStopper#22]
I'm using the version of SnooperStopper currently in the F-Droid repository on a Lineage OS 14.1 custom build (using MicroG and with Root Access enabled).

When I open Snooper Stopper and turn on  "Enable device admin" I am brought to the confirmation screen that say "Activating this administrator will allow this app…" 

I then select "Activate this device administrator" and am brought back to the first screen, however "Enable device admin" is now unchecked. I select enable again, and am looped back through this acceptance screen.

There doesn't seem to be any way out of this loop. Snooper Stopper is not monitoring failed access attempts. Snooper Stopper worked on the device when it was running CM 13.1, so I think it might have something to do with changes in the newer versions.

**Comment by thomasjfox** [comment]
works fine for me on Lineage 14.1 from 2017-06-07.
May be it has been fixed in the meantime?

**Comment by natmey** [comment]
I just rebuilt my version of Lineage, and this problem persists.

I reinstalled Snooper Stopper and it asked for Root again, which I give it. I then go to "Enable Device Admin," but get caught in the same loop described above.

I did notice that Privacy Guard activates when I'm doing this, so perhaps I need to give the app more permissions? @thomasjfox are there any privacy guard settings that you have allowed?

**Comment by thomasjfox** [comment]
> I did notice that Privacy Guard activates when I'm doing this, so perhaps I
> need to give the app more permissions? @thomasjfox are there any privacy
> guard settings that you have allowed?

the privacy guard is not enabled by default on my phone,
so it might be the culprit here.

Cheers,
Thomas

**Comment by nchristensen** [comment]
<s>I also have this issue in on Android 8.1.</s>

After encrypting the phone the device admin enables correctly.

**Comment by anarcat** [comment]
i can't make the admin stuff work on a Fairphone 2 here either, see #30 for details.
